config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboards#index"
  get '/search', to: "dashboards#search"
  resources :users do
    resources :exercises
  end
  resources :friendships, only: [:show, :create, :destroy]
  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  validates :workout, length: { minimum: 5}
  validates :duration_in_minutes, numericality: {
    only_integer: true, greater_than: 0
  }
  validates :workout_date, presence: true

  default_scope {
    where('workout_date > ?', 7.days.ago).order(workout_date: :desc)
  }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User", primary_key: "id", foreign_key: "friend_id"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable
  has_many :exercises
  has_many :friendships
  has_many :friends, through: :friendships, class_name: "User"
  has_many :messages
  has_one :room

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  after_create :create_chatroom

  self.per_page = 15

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def follows_or_same?(new_friend_id)
    friendships.map(&:friend_id).include?(new_friend_id) || self.id == new_friend_id
  end

  def current_friendship(friend_id)
    friendships.where(friend_id: friend_id).try(:first)
  end

  private

  def create_chatroom
    hiphenated_username = full_name.tr(" ", "-")
    Room.create(name: hiphenated_username, user_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_room
    @room ||= Room.find(session[:current_room]) if session[:current_room].present?
  end

  helper_method :current_room
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  # GET /dashboards
  # GET /dashboards.json
  def index
    @athletes = User.paginate(page: params[:page])
  end

  def search
    @athletes = User
      .paginate(page: params[:page])
      .where('first_name LIKE :keywords OR last_name LIKE :keywords
        OR email LIKE :keywords', keywords: "%#{params[:keywords]}%")
    flash[:notice] = "No user found with the requested details" if @athletes.count <= 0
    render :index
  end
end

app/controllers/exercises_controller.rb
# Class for exercises
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :destroy, :edit, :update, :destroy]
  before_action :set_current_room

  def index
    @exercises = current_user.exercises
    @friends = current_user.friends
    @message = Message.new
    @messages = current_user.messages if current_room
    @followers = Friendship.where(friend_id: current_user.id)
  end

  def edit
    @user = current_user
  end

  def show; end

  def new
    @user = current_user
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params.merge(user_id: current_user.id))
    if @exercise.save
      redirect_to user_exercise_path(current_user, @exercise), notice: "Exercise has been created"
    else
      @user = current_user
      flash[:error] = "Exercise has failed to save"
      render :new
    end
  end

  def update
    if @exercise.update(exercise_params)
      redirect_to user_exercise_path(current_user, @exercise), notice: "Exercise Updated Successfully"
    else
      @user = current_user
      render :edit, error: "Failed to update"
    end
  end

  def destroy
    if @exercise.destroy
      flash[:notice] = "Exercise Deleted Successfully"
    else
      flash[:error] = "Failed to delete Exercise"
    end
    redirect_to user_exercises_path(current_user)
  end

  private

  def exercise_params
    params.require(:exercise).permit(:workout, :workout_date, :duration_in_minutes)
  end

  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end

  def set_current_room
    @room = params[:room_id].present? ?  Room.find(params[:room_id]) : current_user.room
    session[:current_room] = @room.id if @room.present?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def show
    @friend = Friendship.find(params[:id]).friend
    @exercises = @friend.exercises
  end

  def create
    unless current_user.follows_or_same?(params[:friend_id])
      Friendship
        .create!(friend_id: params[:friend_id], user_id: current_user.id)
    end
    redirect_to root_path
  end

  def destroy
    friendship = Friendship.find(params[:id])
    if friendship.destroy 
      flash[:notice] = "#{friendship.friend.full_name} unfollowed"
    else
      flash[:alert] = "Couln't unfollow #{friendship.friend.full_name}"
    end
    redirect_to user_exercises_path(current_user)
  end

  private

  def friendships_params
    params.permit(:friend_id, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = current_user.messages.build(messages_params)
    @message.room = current_room

    @message.save
    redirect_to user_exercises_path(current_user)
  end

  private

  def messages_params
    params.require(:message).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="row">
  <div class="col-6 offset-3">
    <div class="jumbotron">
      <h1>Workout lounge</h1>
      <p>Show off your workout</p>
    </div>
  </div>
</div>
<div class="container">
  <h3>List of Members</h3>
  <div class="row">
    <div class="col-12">
      <div class="row heading">
        <div class="col-3">Full Name</div>
        <div class="col-3">E-mail</div>
        <div class="col-3">Member since</div>
        <div class="col-2">Operations</div>
      </div>
      <% @athletes.each do |athlete| %>
        <div class="row">
          <div class="col-3"><%= athlete.full_name %></div>
          <div class="col-3"><%= athlete.email %></div>
          <div class="col-3"><%= athlete.created_at %></div>
          <div class="col-2">
            <% if current_user%>
              <%= link_to "Follow",
                friendships_path(friend_id: athlete.id),
                method: :post,
                class: "btn btn-info pull-right" unless current_user.follows_or_same?(athlete.id)
              %>
            <% end %>
          </div>
        </div>
      <%end %>
    </div>
  </div>
  <div class="row">
    <%= will_paginate @athletes, render: BootstrapPagination::Rails, class: "pull-left paginate" %>
  </div>
</div>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @dashboard.index %>
</p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/exercises/_form.html.erb
<%= form_for [@user, @exercise] do |f|%>
  <div class="form-group">
    <label for="exercise_workout">Workout Details</label>
    <%= f.text_area :workout, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exercise_duration_in_minutes">Duration</label>
    <%= f.text_field :duration_in_minutes, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exercise_workout_date">Activity Date</label>
    <%= f.text_field :workout_date, class: "form-control" %>
  </div>
  <div class="row">
    <div class="col-12">
      <button class="btn btn-primary">Save Exercise</button>
    </div>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h3>Edit Exercise</h3>
<div class="col-8">
  <%= render "form" %>
  <%= link_to "Back", root_path %>
</div>

app/views/exercises/index.html.erb
<%= content_for(:whole_page) do %>
  <div class="row">
    <div class="col-7">
      <div class="card">
        <% if @exercises.present?%>
          <div class="card-heading">
            <div class="row">
              <div class="col-3 card-title">Activity Date</div>
              <div class="col-3 card-title">Duration in minutes</div>
              <div class="col-3 card-title">Description</div>
              <div class="col-3 card-title">Operations</div>
            </div>
          </div>
          <div class="card-content">
            <% @exercises.each do |exercise| %>
              <div class="row">
                <div class="col-3"><%= exercise.workout_date %></div>
                <div class="col-3"><%= exercise.duration_in_minutes %></div>
                <div class="col-3"><%= exercise.workout %></div>
                <div class="col-3">
                  <%= link_to "Edit", edit_user_exercise_path(current_user, exercise) %><br/>
                  <%= link_to "Delete", user_exercise_path(current_user, exercise), method: :delete %>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="alert alert-info">
            <h3>No workout data found</h3>
          </div>
        <% end %>
      </div>
      <div class="col-8">
        <%= link_to "New Workout", new_user_exercise_path(current_user), class: "btn btn-warning" %>
      </div>
    </div>
    <div class="col-5">
      <h1>My Friends</h1>
      <div id="chat-window" class='col-12'>
        <header class="text-center"><%= current_room.name %></header>
        <div class="col-2" id="followers">
          <% @followers.each do |follower| %>
            <%= link_to follower.user.full_name, user_exercises_path(current_user, room_id: follower.user.room.id), class: "followers" %>
            <br/>
          <% end %>
        </div>
        <div class="col-10" id="messages-box">
          <div id="chat-box" data-channel="rooms" data-room-id=<%= current_room.id %>>
            <% @messages.each do |message| %>
              <%= render partial: 'shared/message', locals: { message: message }%>
            <% end %>
          </div>
          <div id="form-box">
            <%= form_for @message do |f| %>
              <div class="input-group">
                <%= f.text_field :body, id: "message-field", class: "form-control" %>
                <div class="input-group-append">
                  <%= f.submit "Post", class: "btn btn-primary", id: "post-btn" %>
                </div>
              </div>
            <% end%>
          </div>
        </div>
      </div>
      <div class="row"><br/></div>
      <% @friends.each do |friend| %>
        <div class="row my-2">
          <div class="col-4">
            <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend.id)) %>
          </div>
          <div class="col-4">
            <%= link_to "Unfollow",
              friendship_path(current_user.current_friendship(friend.id)),
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: "btn btn-success link" %>
          </div>
        </div>
      <% end %>
    </div>
    <%= content_tag :div, "", id: "graph-chart", data: { workouts: @exercises } %>
  </div>
<% end %>

app/views/exercises/new.html.erb
<h3>New Exercise</h3>
<div class="col-8">
  <%= render "form" %>
  <%= link_to "Back", root_path %>
</div>

app/views/exercises/show.html.erb
<div class="row">
  <div class="col-12">
    <h3>Exercise for <%= @exercise.user.email %></h3>
  </div>
</div>
<div class="row">
  <div class="col-3">
    Workout Details
  </div>
  <div class="col-6">
    <%= @exercise.workout %>
  </div>
</div>
<div class="row">
  <div class="col-3">
    Workout Duration
  </div>
  <div class="col-6">
    <%= @exercise.duration_in_minutes %>
  </div>
</div>
<div class="row">
  <div class="col-3">
    Workout Date
  </div>
  <div class="col-6">
    <%= @exercise.workout_date %>
  </div>
</div>

app/views/friendships/show.html.erb
<div class="col-8">
  <h1><%= @friend.full_name %>'s Exercises</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Duration (min)</th>
        <th>Distance</th>
        <th>Activity Date</th>
      </tr>
    </thead>
    <tbody>
      <%= @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.duration_in_minutes %></td>
          <td><%= exercise.workout %></td>
          <td><%= exercise.workout_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br/>
<div class="col-4">
  <%= content_tag :div, "", id: "chart", data: { workouts: @exercises } %>
  <br/>
  <%= link_to "Back", user_exercises_path(current_user), class: "btn btn-success link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= render "shared/navigation" %>
    <%= render "shared/flashes" %>
    <div class="<%= content_for?(:whole_page) ? 'container-fluid' : 'container' %>">
      <%= yield %>
      <%= yield :whole_page%>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div class="container">
    <div class="row">
      <div class="col-8 offset-2">
        <% flash.each do |key, value| %>
          <div 
            class="alert alert-<%= (['error', 'warning'].include?(key)) ? "danger" : "success" %> alert-dismissable fade show"
            role="alert"
          >
            <%= value %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_message.html.erb
<div class="messages-row">
  <p class="message-body"><%= message.body %></p>
  <span>"<small><%= message.user.full_name %></small>"</span>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light my-light">
  <%= link_to "Athletes Den!", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %></a>
      </li>
      <%- if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Lounge", user_exercises_path(user_id: current_user.id), class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%= form_tag search_path, class:"form-inline my-2 my-lg-0", role: "search", method: :get do %>
      <%= text_field_tag :keywords, params[:keywords],
        class:"form-control mr-sm-2",
        type:"search",
        placeholder:"Search",
        "aria-label": "Search"
      %>
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    <% end %>
    <ul class="navbar-nav ml-auto">
      <%- if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <%- else %>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
        <li class="nav-text">
          <span>Signed in as <%= current_user.full_name %></span>
        </li>
      <% end %>
    </ul>
  </div>
</nav>